### ISSUE TITLE
Katarina Armor

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#188]
http://www.nexusmods.com/skyrim/mods/60814

**Comment by Raulfin** [comment]
Record type: Armor
Item Name: Katarina Gloves, Katarina Armor, Katarina Boots, Katarina Plates, Katarina Belts
Item EDID: xxxKatarinaGloves, xxxKatarinaArmor, xxxKatarinaBoots, xxxKatarinaPlates, xxxKatarinaBelts
Material: Leather (some components: the plates, boots, and belts require iron or steel, but overall it's basically leather armor)
Type: Light armor
is it enchanted: No
should enchanted versions be made: No
should it be distributed as random loot: No
Is it a faction item: No
should enchanted versions be distributed: No
is it a unique/quest item: No
does it add custom enchantments: No
should custom enchantment be added to random loot: No
Is it something not listed above: Like I said under material, it's basically leather armor with some metal.

**Comment by Visdagon** [comment]
Added, close
