### ISSUE TITLE
Black mage armor

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#20]
http://www.nexusmods.com/skyrim/mods/9645

**Comment by Raulfin** [comment]
all the light armor variants are converted to heavy. Cloth remains ok.

**Comment by mgcef** [comment]
alright, here it is: http://pastebin.com/jXMtnRPY
i added the leather pieces, so it should be complete now, unless i misssed something, the plate/ebony light pieces checks out alrighty in my game.

**Comment by Raulfin** [comment]
Got the Steel Plate, Ebony and Leather stuff added. How are they for Distribution and Enchanting?

**Comment by mgcef** [comment]
everything's only available by crafting, so it would be neat do have them disrtibuted and enchanted. 
i really have no idea of what leveled lists looks like so i have no idea of where the heavy/light armor leather/steel plate/ebony items would fit in. as for the cloth items, if they're subject to distribution, they could be distrbuted to mages and necromancers and their ilk. 
i won't really be of much use when it comes to distribution, i'm afraid. :D
