### ISSUE TITLE
Ingredients not all being patched with new 1.2 patcher

### ISSUE THREAD

**Issue by MagielBruntink** [Raulfin/PCaPP#267]
Noticed in game that some ingredients yield 0 duration potions, then checking PatchusMaximus.esp with TES5Edit reveals that many ingredients are not being patched. Examples are the Blue/Red/Purple Mountain Flowers, the mushrooms, and many others.

I tried running the 1.1 patcher with the latest XML files and that actually patches all ingredients succesfully.

Something is broken in the new 1.2 patcher!

**Comment by Tascani** [comment]
Yep, confirm. Looks like all ingredients without variation are not patched.

**Comment by Tascani** [comment]
Fixed with newer patcher version.
