### ISSUE TITLE
Axe of Hrothmund

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#313]
http://www.nexusmods.com/skyrim/mods/16751

Record type: Weapon
Item Name: Hrothmund's Axe
Item EDID: PainHrothmundsAxe
Material: DLC2Nordic
Type: Battleaxe
Skill: Heavy Weaponry
is it enchanted: No
should enchanted versions be made: No
should it be distributed as random loot: No
Is it a faction item: No
should enchanted versions be distributed: No
is it a unique/quest item: Yes
does it add custom enchantments: No
should custom enchantment be added to random loot: No
should scroll/staff versions be made: No
Does it add LLs: No
what kind of items does it distribute: (weapons/enchanted weapons/books) n/a
should items be allowed to be added to it (LLs): No
Is it 'Alchemy': No

**Comment by Escavalx** [comment]
The Axe of Hrothmond is actually http://www.nexusmods.com/skyrim/mods/31116/? Another thing to note: a replica version  of this is added by morrowloot 4e.
