### ISSUE TITLE
Bijin Warmaidens

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#314]
http://www.nexusmods.com/skyrim/mods/40038

What about the mod needs support: since PerMa changes some armors, the mod is not 100% working.. some faces will turn grey/dark and look vanilla

**Comment by Escavalx** [comment]
This might just be a load order problem, just tried it out, and I didn't have any problems with them.

**Comment by Raulfin** [comment]
aye it was a load order issue
