### ISSUE TITLE
Some weapon.xml errors

### ISSUE THREAD

**Issue by Auri-ru** [Raulfin/PCaPP#322]
Double material binding for Ash (Wood and Steel) аnd no Iron for Ash Longbow from master, no Draugr for Ash Spawn from Dragonborn. Didn't find myself what weapons patch Wood and Steel.

Modifier "Great" is applying to the all Greatswords. Maybe add space in bindings? Like that:
"Great "

**Comment by Raulfin** [comment]
Fixed all that.
Ash Longbow will be changed to wood and not Iron (about the same as Steel)
Wood and Steel are in the default bindings section, between lines 500-530.
