### ISSUE TITLE
Tera armor bindings for Jalmarak

### ISSUE THREAD

**Issue by Escavalx** [Raulfin/PCaPP#331]
There are two material bindings for Jalmarak armor in the armor.xml, does anyone know offhand if  the misspelled binding is intentional or a mistake?

<binding>
<identifier>Elven</identifier>
<substring>Jalamark</substring>
</binding>

<binding>
<identifier>Elven</identifier>
<substring>Jalmarak</substring>
</binding>

TERA Armors Collection for Skyrim - Male and UNP female by asianboy345 http://www.nexusmods.com/skyrim/mods/25846/? uses Jalmarak

**Comment by Raulfin** [comment]
It may be from one of the following that was added shortly after Noldor Content Patch during beta, or it could be a typo left over from the SkyRe xml;
Wrymstooth
        Falskaar
        OBIS
        OBIS Redone
        Assassin's Creed Ezio Auditore Masyaf cuirass rework
        Cursory support for Hunterborn and Frostfall
        The Way of the Dovahkiin - Ultimate Deadly Encounters aka Sands of Time (SoT)

**Comment by Escavalx** [comment]
Thanks, I'll look through them.

**Comment by Escavalx** [comment]
Finished searching through them, Couldn't find any "Jalamark" armor.

**Comment by Raulfin** [comment]
Prolly just a typo then. Doesn't look like it would be a 'common' typo though.
