### ISSUE TITLE
Much Ado about Snow Elves - A Tragedy - Act I

### ISSUE THREAD

**Issue by Escavalx** [Raulfin/PCaPP#332]
http://www.nexusmods.com/skyrim/mods/16455/? Weapons and shield have elven material keywords, but are clearly ancient falmor, Both by name and by the mod title(they actually have daedric damage instead of glass but w/e) ancient flamor has elven keywords in the base game despite having glass stats anyway.

**Comment by Escavalx** [comment]
There's also a random orcish warhammer that i'm only going to be excluding, as it looks like a test item (named "ZZZ") and has stats higher than dragonbone weaponry

**Comment by Raulfin** [comment]
The ArmorMaterialFalmer keyword was added by Update.esm.
DLC1ArmorMaterialFalmerHardened and DLC1ArmorMaterielFalmerHeavy  were added by Dawnguard, that mod should be using these keywords, or WeapMaterialFalmer if it's a Falmer weapon.
But given it's a 2012 mod it's likely to have other larger issues

**Comment by Escavalx** [comment]
After perusing the dawnguard armor the set is semi-based off of in TESVedit : ArmorMaterialFalmer and the Hardened and Heavy variants aren't used for Ancient Falmor armor. The material is Elven for Dawnguard and UDGP. WAFR swaps Elven for Elven Gilded and adds some of its own keywords. Since gilded is basically demoted to a modifier in PerMa and ancient falmer isn't modified by it, the weapons and shield added by Much Ado About Snow Elves should be functionally the same as the Ancient Falmer Armor added by Dawnguard, besides the non material keywords added by WAFR. On a side note: It might be worth it to change ancient Falmer's materialMeltdown materialTemper to Elven, as CCOR's breakdown material for the Ancient Falmer Set is refined moonstone, the armor isn't made of chitin (more of a elven+ebony mix), and the temper material is refined moonstone.

**Comment by Raulfin** [comment]
The Elven Gilded keyword is checked for in the same places as Elven, it just didn't get it's own material entry since it would be pretty much the same as the Elven entry.
The xml is based on WAFR, will check it out rq.

**Comment by Raulfin** [comment]
Okay, WAFR changed 'Ancient Falmer' to 'Snow Elf' that's why it's Moonstone in CCOR.

**Comment by Raulfin** [comment]
I changed Snow Elf to use ElvenHigh since it's 'Gulded'.

**Comment by Escavalx** [comment]
Alright, what do you want to do for the ancient falmer material binding? Simplest would be to just change the temper/meltdown to Elven, but alternatively, you could get rid of the material binding entirely and make ancient falmer ElvenHigh specific. The base game has moonstone tempering for it as well.

**Comment by Raulfin** [comment]
will change the temper/meltdown to Elven

**Comment by Escavalx** [comment]
I apologize for going on and on with this, but should I add an ancient falmer material binding to the weapons.xml? I didn't actually realize that the armor materials and weapon materials weren't shared.

**Comment by Raulfin** [comment]
there are ancient falmer weapons?

**Comment by Raulfin** [comment]
but ya, if there is a need for it go ahead

**Comment by Escavalx** [comment]
Not in the base game, just for the ones added by Much Ado about Snow Elves
