### ISSUE TITLE
Wrath of Nature, Path of the Druid and The Champion of Kynareth

### ISSUE THREAD

**Issue by Escavalx** [Raulfin/PCaPP#348]
http://www.nexusmods.com/skyrim/mods/31485/?
http://www.nexusmods.com/skyrim/mods/39928/?

**Comment by Escavalx** [comment]
As far as I can tell, this only needs a few armor bindings and a few levelled list exclusions, as the monsters and their spells aren't noticed by the patcher, and it adds books that need to be excluded. I'm going to do a quick run of it later on this week once I finish the xmls and make sure there's nothing crazy.

**Comment by Raulfin** [comment]
any magic mod is going to need an esp patch since a lot of effects have to be added to the spells.

**Comment by Escavalx** [comment]
They're transformation and transformed "monster" spells for the most part. Which I believe shouldn't benefit from PerMa perks. After all, for a flame atronach, it would be more like hurling a piece of your body at them rather than actually casting magic. Forgot about this mod with the move, I'll take a look at it once I get my testing profile running with 1.3.

**Comment by Escavalx** [comment]
Note: magic costs seem high enough to warrant a patch =/
Edit: All abilities use stamina besides original transformation, which is 60 flat Magicka with infinite duration and a Spriggan concentration spell, which uses a considerable amount, but does damage worthy of the cost.

**Comment by Raulfin** [comment]
If it's just costs that shouldn't be a big deal. I can mess with that after release unless you want to.
