### ISSUE TITLE
LUNA, TERRA, MARS and VENUS

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#367]
Part of a PM I got;

LUNA (http://www.nexusmods.com/skyrim/mods/55644): There are two versions of the sword which are incorrectly labelled as [Longsword] when they are Greatsword/Bastard sword: "Luna 2h" and "Luna II", both use the greatsword slot in game, I use DSR and while changing weapons I noticed that one of them was positioned a little higher then the other then I checked with vanilla weapons and realized that it was a greatsword, but labelled as a longsword.

TERRA (http://www.nexusmods.com/skyrim/mods/56049): This mod... This mod, man... The author made so many versions of the weapon it's weird: "Terra", "Black Terra", "Dragonborn Terra" and "Black Dragonborn Terra", all Longswords; The problem here is that there are greatsword versions of all of those, by adding "Great" at the beginning of each.

I've checked all of the weapons that I'm talking about. I even checked the new XML uploaded today (04/13/2015), and saw that you did see the pattern, but didn't notice the rest.

The other two mods by Zikoru: MARS (http://www.nexusmods.com/skyrim/mods/57182) and VENUS (http://www.nexusmods.com/skyrim/mods/56492); know that he did the same thing with those what he did with TERRA, added "Great" to the greatswords.

One more thing before I finish: "Dragonborn Terra" and "Black Dragonborn Terra" are both under ebony on the Crafting menu.

**Comment by slasherjdc** [comment]
We need a new Armor and weapon section for overwrites, because at the moment the sections overwrite going down and it messes up some mods.
