### ISSUE TITLE
Daedric Cresent(LWE/IW) Conflict.

### ISSUE THREAD

**Issue by slasherjdc** [Raulfin/PCaPP#369]
LWE/IW require a patch. Draedric Cresent is a One-hander in 'Immersive Weapons' but a greatsword in 'Lore Weapon Expansion',Unfortunately Greatsword bindings will always overwrite Arming Sword Bindings so either LWE needs a patch to add "Greatsword" or' IW needs a patch and there needs to be another binding section for binding overrides like this.

**Comment by Raulfin** [comment]
Renamed items in IW, the Deadric Crescent is a 2h weapon in lore so LWE is correct.
    Deadric Crescent -> Daedric Crescent - Short (IW)
    Great Deadric Crescent -> Deadric Crescent (IW)
(sic)http://www.uesp.net/wiki/Morrowind:Daedric_Crescent
