### ISSUE TITLE
Imperial Assassin Armour

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#423]
http://www.nexusmods.com/skyrim/mods/55505

Record Type - Armour
Item Name: N/A
Type: Light Armour
it enchanted: No 
should enchanted versions be made: No
should it be distributed as random loot: No
Is it a faction item: No
should enchanted versions be distributed: No
is it a unique/quest item: No 
does it add custom enchantments: No 
should custom enchantment be added to random loot: No 
should scroll/staff versions be made: No 
Does it add LLs: No 
what kind of items does it distribute: N/A
should items be allowed to be added to it : Yes
Is it 'Alchemy': No 
Is it something not listed above: No

**Comment by Visdagon** [comment]
Added, close
