### ISSUE TITLE
Nexus Request: The Ashbringers by johnskyrim

### ISSUE THREAD

**Issue by Yama1291** [Raulfin/PCaPP#432]
Good day gents!
I'm making this request for VampirePrince on the nexus:
"The Ashbringers is showing up as a shortbow in my game. Is there an easy fix I can do in the meantime, TES5editing the patchusmaximus seems overly tedious."

http://www.nexusmods.com/skyrim/mods/65346/?

**Comment by Escavalx** [comment]
I actually just added this with my last commit haha, it should be good to go with the next release.

**Comment by Yama1291** [comment]
Well fuck me :)
Thank you. I'll relay the message.

**Comment by Raulfin** [comment]
#426

**Comment by Yama1291** [comment]
I know, already closed it.

**Comment by Escavalx** [comment]
He's just referencing for proper records.
