### ISSUE TITLE
Twilight (Guild Wars 2 Legendary GreatSword)

### ISSUE THREAD

**Issue by Escavalx** [Raulfin/PCaPP#436]
Nexus quote:
"Is this where I go for PerMa patches? if so, I need help. I found a Twilight GreatSword mod (Guild wars 2) for Skyrim and the perma patcher does not see it as a greatsword. the ONLY perks that work on it are the damage increase perks (Heavy Weapon Combat, both ranks) and critical charge. other then that, I cant really use it. I also have no knowledge of how to fix it myself. can you help me.

here is the link to the mod in question
http://www.nexusmods.com/skyrim/mods/56031/?"

**Comment by Raulfin** [comment]
Twilight (Guild Wars 2 Legendary Greatsword) http://www.nexusmods.com/skyrim/mods/56031/?
Name: Twilight
Material: Daedric (category only, the recipe calls for 25 each of 5-6 different items, including nirnroot [recipe is irrelevant, treat it as its guild wars 2 counterpart])
Type: Two-Handed Greatsword
Is it enchanted: yes, but only so it can display a custom description "Twilight is a legendary greatsword" (if this can be removed so I can actually enchant it, that would be awesome)
Should enchanted versions be made?: Yes (wintermyst, enough said)
Is it unique? Yes.
Is it a quest item? No
Is it a faction item? No
Should enchanted versions be distributed?: No, I wish to use the console to access those.
Side note: the only Twilight in the mod is the custom no effects description enchantment version. not sure if that helps but thought I should put that there

**Comment by Raulfin** [comment]
It wasn't actually enchanted, it just has a description set.
