### ISSUE TITLE
Sexy Ninja Armor

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#464]
http://www.loverslab.com/topic/46665-sexy-ninja-armor

Armor parts named:  
*Sexy Ninja Hood
*Sexy Ninja Mask
*Sexy Ninja Gloves
*Sexy Ninja Leg Straps
*Sexy Ninja Thigh Strap
*Sexy Ninja Thigh Dagger
*Sexy Ninja Back Dagger
*Sexy Ninja Boots
*Sexy Ninja Body Strap
*Sexy Ninja Thong

**Comment by Visdagon** [comment]
Added, close
