### ISSUE TITLE
Dragon Carved Armor Set 

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#476]
http://www.nexusmods.com/skyrim/mods/66130

Special Notes : Set has Cuirass, Cuirass without Pauldron, Helmet, Gauntlets, Boots, Shield, 1 hand sword, Great Sword

Special Notes 2 :
Craft
Armors - Advanced Armors
Weapons - Steel Smithing

Temper
Armors - Advanced Armors

**Comment by Visdagon** [comment]
Added, close
