### ISSUE TITLE
Leveled list issues

### ISSUE THREAD

**Issue by ElArGee** [Raulfin/PCaPP#492]
Just a few issues I noticed in PatchusMaximus.esp:
- Maces and Swords are being added to all non-enchanted WarAxe leveled lists
- Swords are being added to all non-enchanted Dagger leveled lists
- Greatswords and Warhammers are being added to all non-enchanted Battleaxe leveled lists
- Battleaxes and Warhammers are being added to all non-enchanted Greatsword leveled lists
- Shortspears are being added to Dagger leveled lists instead of waraxe LL's
- Katana's, Scimitar (non heavy), and Sabre's are being added to waraxe LL's instead of sword LL's

I've confirmed this on a clean mod loadout with only PerMa loaded. Enchanted leveled lists seem to be unaffected. I'm guessing the cause will likely be in the patcher?
Note: some of the items may be from the weaponry fillout (I will go back and confirm which ones)

The items are still being added to their "normal" LL but are also being added to the other LL's (i.e. swords are still added to the swords LL, but they also have an entry in the waraxe and dagger LL's).

If this is working as intended then disregard.

**Comment by Raulfin** [comment]
Sorry took so long to reply to this. It's intended, PaMa uses a similarity system for distribution, Axes are Blade/Blunt weapons so other Blade and Blunt weapons will be added to lists with them. Same for other weapon types.

**Comment by ElArGee** [comment]
No problem, I'll close this off then since it's working as intended.
