### ISSUE TITLE
Dynamic Potions

### ISSUE THREAD

**Issue by Raulfin** [Raulfin/PCaPP#58]
http://www.nexusmods.com/skyrim/mods/47521

**Comment by Tascani** [comment]
I already posted at the modpage of Dynamic Potions:

This was my message:

"On PerMa compatibility:
Dynamic Potions is compatible with PerMa.

Load order:

PerkusMaximus_Master.esp
[...]
PerMa Expansion 1 - Wintermyst.esp*
DynamicPotions.esp*
PerkusMaximus_Mage.esp
PerkusMaximus_Thief.esp

It must be loaded AFTER Wintermyst and BEFORE Thief_module.

If I got everything right then DynamicPotions changes baseCost and Descriptions to fit the new Duration over <dur> seconds style.
PerMa will do that anyway so there is no conflict.

The following things need attention when using the MCM.

Changed MagicEffects:

Fortify Enchanting -> Brawler
Fortify Lockpicking -> Guardian
Fortify Smithing -> Weaponmaster
Fortify Pickpocket -> Fortify Dexterity

Ravage Magicka -> Flare Undaed (has no MCM entry, just for information)
Ravage Stamina ->Corrode Armor (has no MCM entry, just for information)

There should be no direct conflicts but I couldn't test it extensively.

Please note that the percentage values in the MCM will take the PerMa values and then modify them according to your slider settings, but as all in-game descriptions are correct you can just tune it as usual.

*EDIT:
Loading Dynamic Potions after wintermyst ensures that the description of the Slow effect is correct and gets updated when you change the magnitude of the slow in the MCM.

The author of wintermyst included a small bugfix (application of the slow effect has been made more smooth) in wintermyst, it will be overriden.
But either this - or the description is not correct."
